# 本地开发环境配置
name = "tech-push-dev"
main = "./src/worker/index.ts"
compatibility_date = "2025-01-30"
compatibility_flags = ["nodejs_compat"]

# 本地开发时使用真实的R2 bucket
[[r2_buckets]]
binding = "INSIGHTCAST_BUCKET"
bucket_name = "insightcast-bucket"

# 本地开发时的环境变量
[vars]
ENVIRONMENT = "development"
DEBUG = "true"

# 本地开发时的资源目录
[assets]
directory = "./dist/client" 